version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/results:/app/results
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

  # (Optional) A simple Postgres service if you switch from JSON file storage:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: seo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
