version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/results:/app/results

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

  # Optional Postgres if you later switch from JSON storage
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: seo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
